# Generated by Django 3.2.21 on 2023-09-27 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_auto_20230925_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='group',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_required',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=2),
        ),
    ]
